name: Pull Request
description: Pull request template
title: "XXXXXX [2024/XX/XX] "


body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this pull request template!

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Write a short and explicit description of your request...

  - type: checkboxes
    id: terms
    attributes:
      label: CheckList
      description: Please ensure that you agree to this CheckList before submitting this pull request.
      options:
        - label: Your code builds clean without any errors or warnings
          required: true
        - label: I have performed a self-review of my code
          required: true
        - label: If it is a core feature, I have added thorough tests.
          required: true
        - label: I have respected all the syntax-rules of the project.
          required: true
        - label: I'have checked for spelling mistakes and repetitions 
          required: true

  - type: markdown
    attributes:
      value: |
        Thank you for your contribution.